### ISSUE TITLE
O'reilly missing chapters

### ISSUE THREAD

**Issue by keshav-c** [PacktPublishing/Learning-OpenCV-5-Computer-Vision-with-Python-Fourth-Edition#3]
This is not an issue with this repo but with the O'reilly distribution of your work.
In that, only chapters 5,6 and 7 from this text are included. I want to ask if that is intentional.

Thanks and cheers

<img width="1430" alt="SCR-20240305-htvz" src="https://github.com/PacktPublishing/Learning-OpenCV-5-Computer-Vision-with-Python-Fourth-Edition/assets/6380138/01df0131-11ba-4251-9e2f-9a749323c3ad">

**Comment by JoeHowse** [comment]
Hello, Keshav. Thanks for the query. I am not sure, so I will check with Packt Publishing. Please note that the book is still in Early Access, as OpenCV 5 is still in development.

**Comment by keshav-c** [comment]
I see. The O'Reilly page fails to mention that. In fact it notes the publication date as Feb 2023. Thanks for the clarification.
